In [81]:
#exercice1
import pandas as pd
import numpy as np
import sqlite3
df = pd.read_csv('customers.csv')

In [11]:
df.head(10)

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
0,CUST0001,Uma Brown,uma.brown94@email.com,NaN,Cntrl,Premium,Inactive,70,26 Aug 2020
1,CUST0002,Alice Hall,alice.hall41@email.com,+1-900-714-2983,South,NaN,Active,62,2023-10-25
2,CUST0003,Iris Davis,iris.davis56@email.com,+1-779-901-1672,Central,basic,Inactive,61,2021-02-24
3,CUST0004,Henry Jones,henry.jones78@email.com,+1-555-645-8018,Central,Enterprise,Inactive,45,2023/04/09
4,CUST0005,Xander Brown,xander.brown66@email.com,+1-877-479-2129,East,Enterprise,Suspended,69,2022-09-28
5,CUST0006,Victor Hall,victor.hall15@email.com,+1-718-763-6590,North,basic,active,29,2020-07-05
6,CUST0007,Cleo Thompson,NaN,+1-212-969-7882,West,Enterprise,In-active,24,2022-11-11
7,CUST0008,Carol Robinson,carol.robinson74@email.com,+1-701-208-8102,North,premium,suspended,24,2022-07-01
8,CUST0009,Noah Johnson,noah.johnson25@email.com,+1-570-750-8532,West,Premium,Inactive,51,2020-04-23
9,CUST0010,Alice Williams,alice.williams33@email.com,+1-924-256-8135,North,Basic,Suspended,27,2022-07-17

In [12]:
df.tail(3)

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
312,CUST0109,Paul Smith,paul.smith84@email.com,+1-915-596-2989,West,Basik,Inactive,39,2023-03-25
313,CUST0255,Amara Anderson,amara.anderson29@email.com,+1-356-803-8770,East,Premium,Inactive,54,2020-10-13
314,CUST0211,Victor Lewis,victor.lewis50@email.com,+1-486-133-7070,Centr.,Std,Active,22,2021-09-23

In [14]:
df.shape

(315, 9)

In [20]:
#EXERCICE2
import pandas as pd
df=pd.read_csv('transactions.txt', sep=',')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1210 entries, 0 to 1209
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  1210 non-null   object
 1   customer_id     1210 non-null   object
 2   amount          1158 non-null   object
 3   category        1152 non-null   object
 4   region          1210 non-null   object
 5   status          1165 non-null   object
 6   date            1210 non-null   object
dtypes: object(7)
memory usage: 66.3+ KB

In [24]:
df.memory_usage(deep=True)

Index               132
transaction_id    70180
customer_id       68970
amount            64743
category          64315
region            65281
status            68533
date              71479
dtype: int64

In [25]:
df.memory_usage(deep=True).sum()

np.int64(473633)

In [26]:
#EXERCICE3
df=pd.read_excel('network_usage.xlsx',sheet_name='January')

In [27]:
df.describe()

            data_mb  voice_minutes   sms_count  speed_mbps
count    198.000000     194.000000  192.000000  204.000000
mean     648.097778     289.515464  149.270833   60.087696
std     1501.665694     174.770648   82.245130   83.390482
min        1.270000       1.000000    1.000000  -95.200000
25%      133.582500     130.500000   81.000000   28.297500
50%      316.635000     276.500000  145.000000   53.820000
75%      683.327500     439.750000  219.000000   76.542500
max    12590.920000     592.000000  293.000000  860.350000

Requirement already satisfied: openpyxl in c:\users\general stores\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\general stores\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
#EXERCICE4
pd.read_json('api_data.json')

,api_record_id,customer_id,plan_id,plan_name,monthly_fee,data_limit_gb,data_used_gb,last_updated,auto_renew,discount_pct
0,API00001,CUST0278,P004,Enterprise,99.99,500,338.76,2024-07-25T00:00:00,0.0,28.9
1,API00002,CUST0258,P003,Premium,39.99,100,52.35,2024-09-12T00:00:00,1.0,2.2
2,API00003,CUST0102,P003,Premium,39.99,100,37.36,09/01/2024 00:00,0.0,26.0
3,API00004,CUST0130,P001,Basic,9.99,5,4.5,2024-09-06T00:00:00,NaN,14.0
4,API00005,CUST0198,P001,Basic,9.99,5,15.64,2024-11-30T00:00:00,1.0,17.9
...,...,...,...,...,...,...,...,...,...,...
245,API00246,CUST0109,P003,Premium,39.99,100,95.06,10-Mar-2024,1.0,15.1
246,API00247,CUST0265,P001,Basic,9.99,5,0.44,2024/04/03,NaN,13.6
247,API00248,CUST0288,P003,Premium,39.99,100,425.21,2024-11-24T00:00:00,1.0,2.7
248,API00249,CUST0162,P001,Basic,9.99,5,4.91,2024-04-05T00:00:00,NaN,26.4
249,API00250,CUST0221,P002,Standard,19.99,20,34.96,2024-10-30T00:00:00,1.0,0.1

In [35]:

print(df.shape)

(218, 9)

In [39]:
df.head(5)

,record_id,customer_id,subscription_type,usage_gb,data_mb,voice_minutes,sms_count,speed_mbps,month
0,JAN0001,CUST0081,Standard,18.8,222.18,47.0,230.0,65.36,January
1,JAN0002,CUST0107,Basic,35.67,1230.59,NaN,85.0,90.53,January
2,JAN0003,CUST0111,Enterprise,48.84,427.97,112.0,62.0,9.46,January
3,JAN0004,CUST0277,Standard,125.89,670.07,158.0,NaN,22.44,January
4,JAN0005,CUST0214,Std,24.58,336.79,29.0,292.0,84.60,January

In [40]:
df.dtypes

record_id             object
customer_id           object
subscription_type     object
usage_gb              object
data_mb              float64
voice_minutes        float64
sms_count            float64
speed_mbps           float64
month                 object
dtype: object

In [69]:
#XERCICE5
import sqlite3; conn = sqlite3.connect('telecom.db')

In [72]:
df.dropna()

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
2,CUST0003,Iris Davis,iris.davis56@email.com,+1-779-901-1672,Central,basic,Inactive,61,2021-02-24
3,CUST0004,Henry Jones,henry.jones78@email.com,+1-555-645-8018,Central,Enterprise,Inactive,45,2023/04/09
4,CUST0005,Xander Brown,xander.brown66@email.com,+1-877-479-2129,East,Enterprise,Suspended,69,2022-09-28
5,CUST0006,Victor Hall,victor.hall15@email.com,+1-718-763-6590,North,basic,active,29,2020-07-05
7,CUST0008,Carol Robinson,carol.robinson74@email.com,+1-701-208-8102,North,premium,suspended,24,2022-07-01
...,...,...,...,...,...,...,...,...,...
309,CUST0051,Frank Thompson,frank.thompson79@email.com,+1-388-152-5136,South,enterprise,SUSPENDED,59,2023-10-30
311,CUST0018,Sam Wilson,sam.wilson93@email.com,+1-783-724-7209,West,BASIC,Suspended,35,04 Aug 2022
312,CUST0109,Paul Smith,paul.smith84@email.com,+1-915-596-2989,West,Basik,Inactive,39,2023-03-25
313,CUST0255,Amara Anderson,amara.anderson29@email.com,+1-356-803-8770,East,Premium,Inactive,54,2020-10-13
314,CUST0211,Victor Lewis,victor.lewis50@email.com,+1-486-133-7070,Centr.,Std,Active,22,2021-09-23

In [75]:
pd.read_sql('SELECT * FROM customers', conn)

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
0,CUST0001,Uma Brown,uma.brown94@email.com,None,Cntrl,Premium,Inactive,70,26 Aug 2020
1,CUST0002,Alice Hall,alice.hall41@email.com,+1-900-714-2983,South,None,Active,62,2023-10-25
2,CUST0003,Iris Davis,iris.davis56@email.com,+1-779-901-1672,Central,basic,Inactive,61,2021-02-24
3,CUST0004,Henry Jones,henry.jones78@email.com,+1-555-645-8018,Central,Enterprise,Inactive,45,2023/04/09
4,CUST0005,Xander Brown,xander.brown66@email.com,+1-877-479-2129,East,Enterprise,Suspended,69,2022-09-28
...,...,...,...,...,...,...,...,...,...
295,CUST0296,David Wilson,david.wilson26@email.com,+1-409-408-4460,South,Enterprise,Active,27,2021/07/16
296,CUST0297,Frank Robinson,frank.robinson10@email.com,+1-985-240-5186,Central,Premiun,active,63,2023-01-02
297,CUST0298,Iris Johnson,iris.johnson76@email.com,+1-496-435-2965,West,Premium,Inactive,45,10/08/2021
298,CUST0299,David Clark,david.clark89@email.com,+1-207-609-8055,None,Enterprise,Suspended,68,2020/02/05
299,CUST0300,Noah Anderson,noah.anderson81@email.com,None,North,Premium,Inactive,42,2022-10-25

In [78]:
conn.close()

In [90]:
#EXERCICE6
import sqlite3
df = pd.read_csv('customers.csv')

In [93]:
df.head(5)

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
0,CUST0001,Uma Brown,uma.brown94@email.com,NaN,Cntrl,Premium,Inactive,70,26 Aug 2020
1,CUST0002,Alice Hall,alice.hall41@email.com,+1-900-714-2983,South,NaN,Active,62,2023-10-25
2,CUST0003,Iris Davis,iris.davis56@email.com,+1-779-901-1672,Central,basic,Inactive,61,2021-02-24
3,CUST0004,Henry Jones,henry.jones78@email.com,+1-555-645-8018,Central,Enterprise,Inactive,45,2023/04/09
4,CUST0005,Xander Brown,xander.brown66@email.com,+1-877-479-2129,East,Enterprise,Suspended,69,2022-09-28

In [92]:
df.tail(5)

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
310,CUST0159,Mia Hall,mia.hall37@email.com,NaN,Central,Enterprise,Suspended,66,2023-02-15
311,CUST0018,Sam Wilson,sam.wilson93@email.com,+1-783-724-7209,West,BASIC,Suspended,35,04 Aug 2022
312,CUST0109,Paul Smith,paul.smith84@email.com,+1-915-596-2989,West,Basik,Inactive,39,2023-03-25
313,CUST0255,Amara Anderson,amara.anderson29@email.com,+1-356-803-8770,East,Premium,Inactive,54,2020-10-13
314,CUST0211,Victor Lewis,victor.lewis50@email.com,+1-486-133-7070,Centr.,Std,Active,22,2021-09-23

In [95]:
df.isnull().sum()

customer_id           0
full_name             0
email                21
phone                36
region               12
subscription_type    16
status                0
age                   0
join_date             0
dtype: int64

In [ ]:
# i don't understand why when i use df instead of "customers.isnull().sum()" it fails

In [97]:
#exercice 7
df.describe()

              age
count  315.000000
mean    51.657143
std     78.610889
min      0.000000
25%     32.000000
50%     43.000000
75%     58.500000
max    999.000000

In [98]:
df.describe().loc['mean'].idxmax()

'age'

In [99]:
df.describe().loc['std'].idxmax()

'age'

In [106]:
# EXERCICE8
df_dropped= df.copy();
df_filled= df.copy();
print(f" customers: {df.shape} {"\n"} df_dropped: {df_dropped.shape} {"\n"} df_filled: {df_filled.shape}")

 customers: (315, 9)
 df_dropped: (315, 9)
 df_filled: (315, 9)

In [107]:
df_dropped.dropna(inplace=True)
print(df_dropped.shape)

(234, 9)

In [108]:
#Exercise 09
df.duplicated().sum()

np.int64(15)

In [109]:
df = df.drop_duplicates() 
df

,customer_id,full_name,email,phone,region,subscription_type,status,age,join_date
0,CUST0001,Uma Brown,uma.brown94@email.com,NaN,Cntrl,Premium,Inactive,70,26 Aug 2020
1,CUST0002,Alice Hall,alice.hall41@email.com,+1-900-714-2983,South,NaN,Active,62,2023-10-25
2,CUST0003,Iris Davis,iris.davis56@email.com,+1-779-901-1672,Central,basic,Inactive,61,2021-02-24
3,CUST0004,Henry Jones,henry.jones78@email.com,+1-555-645-8018,Central,Enterprise,Inactive,45,2023/04/09
4,CUST0005,Xander Brown,xander.brown66@email.com,+1-877-479-2129,East,Enterprise,Suspended,69,2022-09-28
...,...,...,...,...,...,...,...,...,...
295,CUST0296,David Wilson,david.wilson26@email.com,+1-409-408-4460,South,Enterprise,Active,27,2021/07/16
296,CUST0297,Frank Robinson,frank.robinson10@email.com,+1-985-240-5186,Central,Premiun,active,63,2023-01-02
297,CUST0298,Iris Johnson,iris.johnson76@email.com,+1-496-435-2965,West,Premium,Inactive,45,10/08/2021
298,CUST0299,David Clark,david.clark89@email.com,+1-207-609-8055,NaN,Enterprise,Suspended,68,2020/02/05
299,CUST0300,Noah Anderson,noah.anderson81@email.com,NaN,North,Premium,Inactive,42,2022-10-25

In [110]:
#Exercise 10
df.iloc[4]

customer_id                          CUST0005
full_name                        Xander Brown
email                xander.brown66@email.com
phone                         +1-877-479-2129
region                                   East
subscription_type                  Enterprise
status                              Suspended
age                                        69
join_date                          2022-09-28
Name: 4, dtype: object

In [112]:
df.iloc[:,2]

0                 uma.brown94@email.com
1                alice.hall41@email.com
2                iris.davis56@email.com
3               henry.jones78@email.com
4              xander.brown66@email.com
                     ...
295            david.wilson26@email.com
296       frank.robinson10@email.com
297            iris.johnson76@email.com
298             david.clark89@email.com
299           noah.anderson81@email.com
Name: email, Length: 300, dtype: object

In [113]:
df.set_index('customer_id', inplace=True)

In [114]:
 df.loc['CUST0080']

full_name                        Eve Lewis
email                eve.lewis80@email.com
phone                      +1-649-227-8679
region                                East
subscription_type                    Basic
status                             active
age                                     63
join_date                       2020-08-19
Name: CUST0080, dtype: object

In [117]:
#Exercise 11
transaction.sort_values('amount', ascending=True)

NameError: name 'transaction' is not defined